name: deployment-trigger-runner

trigger:
  - main

pool:
  vmImage: windows-latest

resources:
  repositories: 
    - repository: remoteRepo 
      type: git
      name: "Graph%20Developer%20Experiences/UHFDeployment"
      endpoint: reusable-deployment-template-connection 

stages:
  - stage: BuildAndTest
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: BuildAndTest

        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm run build
          displayName: 'npm install and build'

        - task: CopyFiles@2
          displayName: 'copy files to: $(Build.ArtifactStagingDirectory)'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/build'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: drop'
          inputs:
            PathtoPublish: '$(build.ArtifactStagingDirectory)'
      
        - template: templates/hello-beta.yml@remoteRepo